### ISSUE TITLE
Tracker App

### ISSUE THREAD

**Issue by smithdc1** [django/djangobench#38] opened 2020-10-15 19:48 UTC
Hi @adamchainz,

So I've made a bit more progress and I've now made a "thing", which I thought it worth sharing at this stage. I've thoroughly enjoyed this little project so far, so even if not useful (although I hope it will be), the lessons learned here are valuable for me personally. 

Anyway, I've set up a [GitHub action](https://github.com/smithdc1/djangobench-tracker) to run djangobench and to publish the outputs in a datasette. I've currently got it running benchmarks at the rate of one commit per hour, to build up a bit of history. 

https://djangobench-tracker.herokuapp.com/django/bench

The next step is to have a think about how to visualise this data. There are some charting options in the datasette already, but would be good to have a more dashboard approach... Something like this maybe?

https://speed.python.org/comparison/

(Sidenote, interesting that django templates are much faster in 3.7 and 3.8 than 3.6, with 3.9 being faster again. )

**Comment by charettes** [comment] 2020-10-15 20:18
Thank you so much for working on this @smithdc1!

Once this is setup I think I'd be great if we could generate data for older versions of Django as well so we might be able to spot potential regressions we might have missed over the years.

**Comment by adamchainz** [comment] 2020-10-15 22:50
This is awesome!!

> (Sidenote, interesting that django templates are much faster in 3.7 and 3.8 than 3.6, with 3.9 being faster again. )

Yes, really nice that CPython is getting faster.

> Once this is setup I think it'd be great if we could generate data for older versions of Django as well

Yes this would be neat. I think @charettes might be thinking of this "first import speed" regression I found recently... https://github.com/django/django/pull/13443 . This didn't take much effort, I'm sure there are some other low hanging fruit out there.

(On that note, can we add a benchmark for "first import", perhaps using `importlib`? I'm not sure exactly how to do it.)

It would also be nice to have some details about the commits in the datasette DB, so we could chart over time, not just commit hash.

**Comment by smithdc1** [comment] 2020-10-16 07:31
Thank you both for the comments. 

> Once this is setup I think it'd be great if we could generate data for older versions of Django as well so we might be able to spot potential regressions we might have missed over the years.

I've turned up the "speed" to try and build up some history a bit quicker. It's running tests at c.100 commits per day, will look to see if I push it further later. 

> It would also be nice to have some details about the commits in the datasette DB, so we could chart over time, not just commit hash.

The Django commit history is also in the datasette DB, so a custom SQL query can help with this. [See Example](https://djangobench-tracker.herokuapp.com/django?sql=select+c.committer_date+as+commit_date%2C%0D%0A+++++++bench.name%2C%0D%0A+++++++result_avg_base%2C%0D%0A+++++++result_avg_changed%2C%0D%0A+++++++result_delta_avg%2C%0D%0A+++++++result_t_msg%2C%0D%0A+++++++experiment_commit%2C%0D%0A+++++++message%2C%0D%0A+++++++ra.name++++++++++as+committer%2C%0D%0A+++++++rb.name++++++++++as+author%0D%0A%0D%0Afrom+bench%0D%0A+++++++++join+commits+c+on+c.sha+%3D+bench.experiment_commit%0D%0A+++++++++join+raw_authors+ra+on+c.raw_committer+%3D+ra.id%0D%0A+++++++++join+raw_authors+rb+on+c.raw_author+%3D+rb.id%0D%0A%0D%0Awhere+bench.name+is+%22query_delete%22%0D%0A%0D%0Aorder+by+c.committer_date+DESC%0D%0A%0D%0A#g.mark=bar&g.x_column=experiment_commit&g.x_type=ordinal&g.y_column=result_avg_changed&g.y_type=quantitative)

**Comment by adamchainz** [comment] 2020-10-21 18:13
> The Django commit history is also in the datasette table, so a custom SQL query can help with this. See Example

Ah great, this was just my ignorance.

Browsing the data it looks like there's a lot of noise. Many of the commits seems to move up/down and are marked as significant, in one direction or the other, by the checker, but I'd bet they aren't.

I think we might want to change the way benchmarking works to fix this. I'm not sure of the best practices here, though I've heard taking the minimum of N runs, as opposed to the average, makes sense, since CPU noise is only ever additive. I also wonder if we'd want to run each commit multiple times on GitHub Actions, since it's virtualized and runs could be easily affected by noisy neighbours.

**Comment by smithdc1** [comment] 2020-10-26 21:42
Hi Adam, yes it is very noisy. I'm not sure if we can improve this so we get much more steady results but I think there are a few things worth exploring: 

- We're "only" running 100 runs. Can we increase this number based on the speed of the test rather than being a fixed number. I think %timeit works in this way? 

- We already run each commit twice (once as control, once as master), but as you say many are marked as significant. I think there is something in this function that isn't working right. I can run tests on my own laptop and repeatedly get significant differences. 

- Most commits won't impact the performance of every test. Therefore we're sort of running each commit multiple times as the underlying code probably hasn't changed. 

- I'm wondering if longer-term trends can factor out the 'noise'. For example, here is a chart of `query_delete` (two lines for control/experiment). It is fairly obvious there was a [commit](https://github.com/django/django/commit/972000420e08703dd4981466ff67adcd5a61ad4b) that impacted performance here (in a good way as here commits closer to 0 are more recent)

![image](https://user-images.githubusercontent.com/39445562/97230344-ae9c1380-17d1-11eb-9fcd-d450df4e99e9.png)

Final note today is that I'm going to have to think about Heroku. Someone is repeatedly pinging the API which is keeping the server awake (even though I shut it down every after each push / 15mins). I'm therefore running out of free hours. Expect it to stop working in the next day or so.

**Comment by adamchainz** [comment] 2020-10-27 22:28
Nice to see delete got faster.

I've just bumped into pyperf, a new module by python core dev Victor Stinner. It looks like it could be a good base to build upon, rather than developing our custom recording/metrics/comparison tooling.

**Comment by smithdc1** [comment] 2020-10-29 07:40
https://asv.readthedocs.io/en/stable/using.html

This tool also looks interesting. It built upon pyperf. 

🕵️

**Comment by charettes** [comment] 2020-12-10 17:20
We might also want to use cachegrind to stabilize the results https://pythonspeed.com/articles/consistent-benchmarking-in-ci/

**Comment by adamchainz** [comment] 2020-12-10 23:06
cachegrind, and [Itamar's related script](https://github.com/pythonspeed/cachegrind-benchmarking), does look like a good find.

**Comment by smithdc1** [comment] 2021-01-14 20:58
Hi all 👋 

A short(ish) update on this topic.

The Djangobench tracker stopped working a little while ago as the database hit the size limit of 100mb. I've now stopped that from updating. 

I've been instead looking at ASV (mentioned above), and been making some good progress with this. I love the fact you get a sharable website out of the box. I've ported some of the benchmarks already and I've got a few more that I need to review and push. Here's the [view](https://smithdc1.github.io/django-asv/) of progress at about a week ago. 

This new method is already having a few benefits. It spotted and led me to fix a regression in  `resolve()` https://github.com/django/django/commit/622fcb81199864cad1ec9d0b25820a96ef3f586f It also spotted a much larger impact when the ASGI handler was introduced, a ticket is [here](https://code.djangoproject.com/ticket/32312) but this looks a bit tricky to fix (certainly more a complex issue than I can help with!).

**Comment by adamchainz** [comment] 2021-01-14 22:20
👍  Love the ASV results. And amazing that you've got concrete numbers on those regressions.

**Comment by pope1ni** [comment] 2021-02-11 16:37
Hi @smithdc1 

This is looking great so far. A while back I independently had a dabble with ASV, but didn't make as much progress as you have. I'm interested in helping out with some conversion of benchmarks, and there are some other potential benchmarks I wanted to write, e.g. django/django#13906.

Maybe it's worth getting a little team together?

**Comment by carltongibson** [comment] 2021-02-11 19:36
I also mentioned this as an idea for GSoC, so we may get a student interested in that.

**Comment by smithdc1** [comment] 2021-02-13 09:58
Hi @pope1ni 

Firstly, thanks for your kind words. :+1: 

I think some discussion on the topic would be welcomed. I have a fair few things that are in my head which I'm not quite sure what the answer is, and if we do get some interest from a GSoC student it will probably be a useful context for them. Certainly, I feel it's a little sporadic and some structure would help to "take it to the next level".

In the meantime, I'll grant you access to the django-asv repo.

**Comment by muskanvaswan** [comment] 2021-03-25 22:59
Hi,

I want to contribute to Django this GSoC, and this seems like a very useful way to contribute. My experience with ASV and benchmarking, in general, is almost close to none. Although, I'm quite comfortable with Django and have contributed to it in the past to some extent. 
It would be great if you could point me in the correct direction as to where I could start my research into this issue and if there are any specific things I should look out for/focus on.

Thanks 
Muskan Vaswan

**Comment by carltongibson** [comment] 2021-03-28 06:38
@muskanvaswan Did you get up and running? Are you able to run the benchmarks locally? I guess that's the first step. See @smithdc1's opening comment https://github.com/django/djangobench/issues/38#issue-722630338 — there's lots of info there. 

For GSoC we need students who show initiative. There's plenty of info here. It's up to you to take it, run with it, and impress us that you can deliver a great project. The idea is that that is fun and rewarding for you, but we don't have a ready-baked TODO list.

**Closed** 2021-06-18 18:59 UTC

**Comment by smithdc1** [comment] 2021-08-10 06:21
Hi All,

Following on from discussion on [this ticket](https://code.djangoproject.com/ticket/33007) the topic of running the benchmarks came up again. I had started to collect some thoughts following a chat I had with Carlton earlier in the year but hadn't got round to the finishing touches until being spurred on by the recent discussion. Happy to post this on the mailing list if we need to take the discussion there, let me know. 

--------

Hi all,

I spent some time earlier in the year looking at Django's current benchmark suite at Django bench. Which seemed to attract a fair amount of interest.

Key things I found were:


- Pyperf is lovely for writing short benchmarks, bit isn't really designed for a large suite and tracking changes over time
- ASV is better as a benchmarking framework and is used across a number of projects. I migrated most/all(?) of the existing Django bench scripts to ASV. There's a webpage here that shows the output. See [here](https://smithdc1.github.io/django-asv/#forms.FormBenchmarks.time_form_clean)
- running benchmarks in GitHub is possible, but very noisy. It's hard to track regressions. See [here](https://github.com/django/djangobench/issues/38#issuecomment-716840263)
- running them locally is better but not sustainable, we need to automate this. See the machine on the asv link... I'm running them on my raspberry pi, I'm sure we can do better. 

I think the next steps for this work are:

- Where are we missing coverage in the current benchmark suite? We should focus on the core request/response cycle. We seem to have very little coverage for this today? 🤔 
- how do we automate the suite. It would be good to run it once a day / week so we can track performance and catch regressions quickly. I also wonder if we could have something like 'buildbot run benchmarks' so it can be run on an individual PR. As mentioned above running on GH servers is to noisy.
- I think we should encourage folk to add to the benchmark suite when they add a PR that improves performance so we can build up the suite over time. However, as @kezabelle mentioned recently on IRC this is _another_ thing to learn. Therefore the the barrier to entry is rather high, especially without docs. Also I'm not quite sure yet how to use ASV when developing improvements, I prefer `pyperf` for this and others will prefer just `timeit`. I think we need a how-to guide for ASV. 

I think the key next step is to get it running _somewhere_. Once it's more visible I think folk will find it easier to contribute to the other areas.


Thanks

David

**Comment by carltongibson** [comment] 2021-08-10 06:43
Cc @django/triage-review

**Comment by smithdc1** [comment] 2021-08-18 16:32
https://labs.quansight.org/blog/2021/08/github-actions-benchmarks/

Saw this today, which talks about running benchmarks using GitHub actions. My take away is that while possible, running on your own infrastructure should be better.

**Comment by charettes** [comment] 2021-09-20 13:12
Sorry for the long delay in answering here, I had limited time to contribute to OSS in the past month.

> Where are we missing coverage in the current benchmark suite? We should focus on the core request/response cycle. We seem to have very little coverage for this today? 🤔

I think having benchmarks around request life cycle is a good candidate since there was a lot of changes in this area in the past months/releases due to the introduction of async support.

> how do we automate the suite. It would be good to run it once a day / week so we can track performance and catch regressions quickly. I also wonder if we could have something like 'buildbot run benchmarks' so it can be run on an individual PR. As mentioned above running on GH servers is to noisy.

I remember that Anssi was running the suite on his own infra to get more stable results. Could we possibly have a remote Jenkins executor (running somewhere stable) that reports back to an ASV instance hosted on Django infra? Using Jenkins would allow us to leverage the existing Github PR integration when necessary.

> I think we should encourage folk to add to the benchmark suite when they add a PR that improves performance so we can build up the suite over time. However, as kezabelle mentioned recently on IRC this is another thing to learn. Therefore the the barrier to entry is rather high, especially without docs. Also I'm not quite sure yet how to use ASV when developing improvements, I prefer pyperf for this and others will prefer just timeit. I think we need a how-to guide for ASV.

I agree that we need to provide proper documentation if we want to make this a requirement to some form of contributions. Maybe we could only start by setting up ASV to run on a daily basis to get more familiarity with the tooling ourselves and then document our regression testing process along the way?

**Comment by Himanshu-Balasamanta** [comment] 2021-12-26 07:12
> I also mentioned this as an idea for GSoC, so we may get a student interested in that.

Will this Idea also be part of GSoC for 2022?
